(function() {var implementors = {};
implementors["tower_add_origin"] = [{text:"impl&lt;T, B&gt; <a class=\"trait\" href=\"https://docs.rs/tower/0.2.0/tower_service/trait.Service.html\" title=\"trait tower_service::Service\">Service</a>&lt;<a class=\"struct\" href=\"https://docs.rs/http/0.1.16/http/request/struct.Request.html\" title=\"struct http::request::Request\">Request</a>&lt;B&gt;&gt; for <a class=\"struct\" href=\"tower_add_origin/struct.AddOrigin.html\" title=\"struct tower_add_origin::AddOrigin\">AddOrigin</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://docs.rs/tower/0.2.0/tower_service/trait.Service.html\" title=\"trait tower_service::Service\">Service</a>&lt;<a class=\"struct\" href=\"https://docs.rs/http/0.1.16/http/request/struct.Request.html\" title=\"struct http::request::Request\">Request</a>&lt;B&gt;&gt;,&nbsp;</span>",synthetic:false,types:["tower_add_origin::AddOrigin"]},];
implementors["tower_http_util"] = [{text:"impl&lt;'a, T, ReqBody&gt; <a class=\"trait\" href=\"https://docs.rs/tower/0.2.0/tower_service/trait.Service.html\" title=\"trait tower_service::Service\">Service</a>&lt;<a class=\"struct\" href=\"https://docs.rs/http/0.1.16/http/request/struct.Request.html\" title=\"struct http::request::Request\">Request</a>&lt;ReqBody&gt;&gt; for <a class=\"struct\" href=\"tower_http_util/service/struct.AsService.html\" title=\"struct tower_http_util::service::AsService\">AsService</a>&lt;'a, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"tower_http_util/service/trait.HttpService.html\" title=\"trait tower_http_util::service::HttpService\">HttpService</a>&lt;ReqBody&gt;,&nbsp;</span>",synthetic:false,types:["tower_http_util::service::as_service::AsService"]},{text:"impl&lt;T, ReqBody&gt; <a class=\"trait\" href=\"https://docs.rs/tower/0.2.0/tower_service/trait.Service.html\" title=\"trait tower_service::Service\">Service</a>&lt;<a class=\"struct\" href=\"https://docs.rs/http/0.1.16/http/request/struct.Request.html\" title=\"struct http::request::Request\">Request</a>&lt;ReqBody&gt;&gt; for <a class=\"struct\" href=\"tower_http_util/service/struct.IntoService.html\" title=\"struct tower_http_util::service::IntoService\">IntoService</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"tower_http_util/service/trait.HttpService.html\" title=\"trait tower_http_util::service::HttpService\">HttpService</a>&lt;ReqBody&gt;,&nbsp;</span>",synthetic:false,types:["tower_http_util::service::into_service::IntoService"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
